### ISSUE TITLE
remove only-warn

### ISSUE THREAD

**Issue by UziTech** [atom-ide-community/eslint-config-atomic#2]
With the only-warn plugin the ci won't fail if the code isn't linted. This seems like a bad idea.

**Comment by UziTech** [comment]
I'm not sure what the point of not failing if there are errors, but this can be done without this plugin.

```sh
eslint .; exit 0
```

**Comment by aminya** [comment]
I can create a strict variant if you like the linter to throw errors.

**Comment by aminya** [comment]
@UziTech You can use the strict version like this: https://github.com/atom-ide-community/eslint-config-atomic#strict-version
